Update bashpr

diff --git a/bashpr b/bashpr
--- a/bashpr
+++ b/bashpr
@@ -1,18 +1,18 @@
 #!/bin/bash
+echo "Nb_threads,Measure_1,Measure_2,Measure_3,Measure_4,Measure_5" > prcon.csv
 
-echo "Nb_threads,Measure_1,Measure_2,Measure_3,Measure_4,Measure_5" > pr.csv
-gcc -o philosopher prcon.c -pthread
-for i in 2 4 8 16 32; do
-  echo -n "Threads: $i"
-  echo -n "$i," >> pr.csv
-  for _ in 1 2 3 4 5; do
-    make -s clean 2>> err.log
-    { time ./philosopher $i > /dev/null; } 2> /tmp/measure
-    cat /tmp/measure | grep real | awk '{print $2}' | tr -d "\n" >> pr.csv
-    echo -n ";" >> pr.csv
-  done
-  echo "" >> pr.csv
+gcc -o producers_consumers prconver.c -pthread || { echo "Compilation failed!"; exit 1; }
+for total_threads in 2 4 8 16 32; do
+    echo -n "Threads: $total_threads"
+    num_producers=$((total_threads / 2))
+    num_consumers=$((total_threads / 2))
+    echo -n "$total_threads," >> prcon.csv
+    for _ in 1 2 3 4 5; do
+        TIME=$( { time ./producers_consumers $num_producers $num_consumers > /dev/null; } 2>&1 | grep real | awk '{print $2}')
+        echo -n "$TIME;" >> prcon.csv
+    done
+    echo "" >> prcon.csv
 done
 
 # Message de fin
-echo "Mesures collectées et enregistrées dans measures.csv"
+echo "Mesures collectées et enregistrées dans prcon.csv"
